name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm lint
      - run: pnpm test
      - name: Docs guard
        run: pnpm docs:guard
        env:
          BASE_REF: ${{ github.base_ref }}
